/**
 * Generates playable HTML/CSS/JS game code using Gemini
 */
export async function generateGameCode(
  gameDescription: string,
  genre: string
): Promise<string> {
  const apiKey = process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    throw new Error('GOOGLE_API_KEY environment variable is not set');
  }

  const prompt = `You are an expert 3D game developer AI. Generate a complete, playable HTML/CSS/JavaScript horror game with 3D graphics based on this description:

Description: ${gameDescription}
Genre: ${genre}

CRITICAL REQUIREMENTS:
1. **USE THREE.JS FOR 3D GRAPHICS** - Include Three.js from CDN in your code
2. Generate ONLY <style> and <script> tags with complete game code
3. Create 3D characters, environments, and objects using Three.js
4. Add realistic lighting, shadows, and textures for horror atmosphere
5. Implement first-person or third-person 3D camera controls
6. Use keyboard controls (WASD for movement, mouse for looking around)
7. Add 3D collision detection and physics
8. Include atmospheric fog, particle effects, and post-processing
9. Make it fully playable with clear objectives and win/lose conditions
10. Keep it optimized and responsive (60 FPS target)

3D GAME ELEMENTS TO INCLUDE:
- 3D character models (player and NPCs/enemies)
- 3D environment (rooms, corridors, outdoor areas)
- 3D objects (doors, keys, items, furniture)
- Realistic lighting (point lights, spotlights, ambient)
- Shadows and fog for horror atmosphere
- Particle effects (dust, smoke, blood)
- Smooth camera movement and controls

TECHNICAL REQUIREMENTS:
- Include Three.js: <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
- Use document.getElementById('game-container') as the root element
- Create a full-screen 3D canvas
- Implement proper game loop with requestAnimationFrame
- Add collision detection for 3D objects
- Include clear on-screen instructions
- Implement window.getGameState() and window.setGameState(state) for save/load
- Call window.sendGameState(state) when game state changes

HORROR ATMOSPHERE:
- Dark, moody lighting with limited visibility
- Creepy ambient sounds (use Web Audio API)
- Sudden scares and tension building
- Eerie fog and particle effects
- Realistic shadows and darkness

GAME STRUCTURE:
- Start with a title screen and instructions
- Clear objective (escape, survive, find items, etc.)
- Progressive difficulty
- Win and lose conditions
- Score or progress tracking

Do NOT include <!DOCTYPE>, <html>, <head>, or <body> tags.
Start directly with <style> and <script> tags.

Generate a complete, working 3D horror game now:`;

  console.log('[Game Generator] Calling Gemini API...');

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.9,
          maxOutputTokens: 8000,
        },
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error('[Game Generator] Gemini API error:', {
      status: response.status,
      statusText: response.statusText,
      body: errorText,
    });
    throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
  }

  const data = await response.json();
  console.log('[Game Generator] Gemini response received:', {
    hasCandidates: !!data.candidates,
    candidatesLength: data.candidates?.length,
  });

  const gameCode = data.candidates?.[0]?.content?.parts?.[0]?.text || "";

  if (!gameCode) {
    console.error('[Game Generator] No game code in response:', data);
    throw new Error('No game code generated by AI');
  }

  console.log('[Game Generator] Raw game code length:', gameCode.length);

  // Clean up the code (remove markdown code blocks if present)
  const cleanCode = gameCode
    .replace(/```html\n?/g, "")
    .replace(/```javascript\n?/g, "")
    .replace(/```\n?/g, "")
    .trim();

  console.log('[Game Generator] Clean code length:', cleanCode.length);

  if (cleanCode.length < 100) {
    throw new Error('Generated game code is too short or invalid. Please try again with a different description.');
  }

  return cleanCode;
}
